### ISSUE TITLE
`m!` macro reaches recursion_limit with few arguments

### ISSUE THREAD

**Issue by akshayknarayan** [dtolnay/mashup#19]
The `m!` macro appears to grow its recursion depth exponentially with the number of arguments.

This works as expected:
```rust
#[macro_use]
extern crate mashup;

macro_rules! foo {
    ( $s:ident => $($x: ident : $t: ty),+ ) => {
        mashup! { $(
            m["fname" $x] = with_ $x;
        )* }

        m! {
        impl $s { $(
            pub fn "fname" $x (mut self, val: $t) -> Self { self.$x = val; self }
        )* }}
    };
}

#[derive(Default,Debug)]
struct A {
    a: u32,
    b: u32,
}

foo!(A => 
    a: u32,
    b: u32
);

fn main() {
    let a = A::default();
    let v = a
        .with_a(42)
        .with_b(43);
    println!("{:?}", v);
}
```

becomes: 
```
...
#[allow(unused)]
enum ProcMacroHack {
    Input = (
        "m [ \"fname\" a ] = with_ a ; m [ \"fname\" b ] = with_ b ;",
        0,
    )
        .1,
}
impl A {
    pub fn with_a(mut self, val: u32) -> Self {
        self.a = val;
        self
    }
    pub fn with_b(mut self, val: u32) -> Self {
        self.b = val;
        self
    }
}
...
```

However, adding a single extra field to the struct, i.e.,
```rust 
//...
#[derive(Default,Debug)]
struct A {
    a: u32,
    b: u32,
    c: u32,
}

foo!(A => 
    a: u32,
    b: u32,
    c: u32
);
//...
```

fails, with:
```
⇒  cargo expand
    Checking macrotest v0.1.0 (...)
error: recursion limit reached while expanding the macro `m`
  --> src/main.rs:24:1
   |
24 | / foo!(A =>
25 | |     a: u32,
26 | |     b: u32,
27 | |     c: u32
28 | | );
   | |__^ in this macro invocation
   |
   = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
error: aborting due to previous error
error: Could not compile `macrotest`.
To learn more, run the command again with --verbose.
No such file or directory (os error 2)
```

adding  ```#![recursion_limit="128"]``` as the compiler suggests, resolves this. 
However, I would like to follow this pattern for a struct with several fields - is there another way other than increasing `recursion_limit` to some arbitrarily high value?

**Comment by dtolnay** [comment]
The recursion depth does grow with the number of arguments. This is how TT muncher macros work.
https://danielkeep.github.io/tlborm/book/pat-incremental-tt-munchers.html

What makes you suspect that the recursion depth is exponential in the number of arguments?

**Comment by akshayknarayan** [comment]
You are correct, my mistake.

Min recursion depth for given number of fields:
2 fields: `#![recursion_limit="51"]`
3 fields: `#![recursion_limit="73"]`
4 fields: `#![recursion_limit="95"]`
5 fields: `#![recursion_limit="117"]`

So the growth is linear. It seems the compiler's suggestion to double the recursion_limit misled me.

Thanks!
